/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package window;

import convert.CurrencyConvert;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author eynar
 */
public class CurrencyWindow extends javax.swing.JFrame {

    private String currency1 = "";
    private String currency2 = "";
    private Double cambio;
    private String cantidad = "";
    private Double dinero;

    private CurrencyConvert currencyConvert;
    private HashMap<String, Double> tasasDeCambio;

    public CurrencyWindow() {
        initComponents();
        setSize(450, 300);
        setLocationRelativeTo(null);

        currencyConvert = new CurrencyConvert();
        currencyConvert.CambioDinero();
        tasasDeCambio = currencyConvert.getTasaDeCambio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        CurrencyTitle = new javax.swing.JLabel();
        currencyListOne = new javax.swing.JComboBox<>();
        currencyOne = new javax.swing.JTextField();
        currencyReverse = new javax.swing.JButton();
        currencyLabelOne = new javax.swing.JLabel();
        currencyLabelTwo = new javax.swing.JLabel();
        currencyTwo = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        MainMenu = new javax.swing.JMenuItem();
        CurrencyConverter = new javax.swing.JMenuItem();
        TemperatureConverter = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(64, 28, 42));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        CurrencyTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        CurrencyTitle.setForeground(new java.awt.Color(255, 255, 255));
        CurrencyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrencyTitle.setText("Conversor de Moneda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(CurrencyTitle, gridBagConstraints);

        currencyListOne.setBackground(new java.awt.Color(33, 1, 35));
        currencyListOne.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        currencyListOne.setForeground(new java.awt.Color(255, 255, 255));
        currencyListOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolivianos (Bs) a Dólar ($)", "Bolivianos (Bs) a Euro (€)", "Bolivianos (Bs) a Libras Esterlinas (£)", "Bolivianos (Bs) a Yen Japonés (¥)", "Bolivianos (Bs) a Won sur-coreano (₩)" }));
        currencyListOne.setBorder(null);
        currencyListOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyListOneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(currencyListOne, gridBagConstraints);

        currencyOne.setBackground(new java.awt.Color(33, 1, 35));
        currencyOne.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        currencyOne.setForeground(new java.awt.Color(255, 255, 255));
        currencyOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currencyOne.setCaretColor(new java.awt.Color(255, 255, 255));
        currencyOne.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currencyOneKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(currencyOne, gridBagConstraints);

        currencyReverse.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        currencyReverse.setText("Reverse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(currencyReverse, gridBagConstraints);

        currencyLabelOne.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        currencyLabelOne.setForeground(new java.awt.Color(204, 204, 204));
        currencyLabelOne.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currencyLabelOne.setText("Bs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(currencyLabelOne, gridBagConstraints);

        currencyLabelTwo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        currencyLabelTwo.setForeground(new java.awt.Color(204, 204, 204));
        currencyLabelTwo.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(currencyLabelTwo, gridBagConstraints);

        currencyTwo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        currencyTwo.setForeground(new java.awt.Color(204, 204, 204));
        currencyTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currencyTwo.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(currencyTwo, gridBagConstraints);

        MenuBar.setBackground(new java.awt.Color(64, 28, 42));
        MenuBar.setBorder(null);
        MenuBar.setForeground(new java.awt.Color(204, 204, 204));
        MenuBar.setBorderPainted(false);

        FileMenu.setBackground(new java.awt.Color(33, 1, 35));
        FileMenu.setBorder(null);
        FileMenu.setForeground(new java.awt.Color(204, 204, 204));
        FileMenu.setText("Archivo");
        FileMenu.setBorderPainted(false);
        FileMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        MainMenu.setBackground(new java.awt.Color(33, 1, 35));
        MainMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MainMenu.setForeground(new java.awt.Color(204, 204, 204));
        MainMenu.setText("Inicio");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        FileMenu.add(MainMenu);

        CurrencyConverter.setBackground(new java.awt.Color(33, 1, 35));
        CurrencyConverter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CurrencyConverter.setForeground(new java.awt.Color(204, 204, 204));
        CurrencyConverter.setText("Conversor de Moneda");
        CurrencyConverter.setBorder(null);
        CurrencyConverter.setBorderPainted(false);
        CurrencyConverter.setEnabled(false);
        FileMenu.add(CurrencyConverter);

        TemperatureConverter.setBackground(new java.awt.Color(33, 1, 35));
        TemperatureConverter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TemperatureConverter.setForeground(new java.awt.Color(204, 204, 204));
        TemperatureConverter.setText("Conversor de Temperatura");
        TemperatureConverter.setBorder(null);
        TemperatureConverter.setBorderPainted(false);
        TemperatureConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperatureConverterActionPerformed(evt);
            }
        });
        FileMenu.add(TemperatureConverter);

        separator.setBackground(new java.awt.Color(33, 1, 35));
        FileMenu.add(separator);

        Exit.setBackground(new java.awt.Color(33, 1, 35));
        Exit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(204, 204, 204));
        Exit.setText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        FileMenu.add(Exit);

        MenuBar.add(FileMenu);

        HelpMenu.setBackground(new java.awt.Color(33, 1, 35));
        HelpMenu.setForeground(new java.awt.Color(204, 204, 204));
        HelpMenu.setText("Ayuda");
        HelpMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MenuBar.add(HelpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TemperatureConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperatureConverterActionPerformed
        TemperatureWindow temperatureWindow = new TemperatureWindow();
        temperatureWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_TemperatureConverterActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        MainWindow mainWindow = new MainWindow();
        mainWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_MainMenuActionPerformed

    private void currencyOneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currencyOneKeyTyped
        char inputChar = evt.getKeyChar();
        int caretPosition = currencyOne.getCaretPosition();

        try {
            if (Character.isDigit(inputChar) || inputChar == '.') {
                if (inputChar == '.' && cantidad.contains(".")) {
                    evt.consume();
                    return;
                }

                String selectedText = currencyOne.getSelectedText();
                if (selectedText != null) {
                    int selectionStart = currencyOne.getSelectionStart();
                    int selectionEnd = currencyOne.getSelectionEnd();
                    cantidad = cantidad.substring(0, selectionStart) + cantidad.substring(selectionEnd);
                    caretPosition = selectionStart;
                }
                StringBuilder builder = new StringBuilder(cantidad);
                if (!cantidad.isEmpty() && caretPosition < cantidad.length()) {
                    builder.setCharAt(caretPosition, inputChar);
                } else {
                    builder.append(inputChar);
                }
                cantidad = builder.toString();
                //cantidad += cantidad.substring(0, caretPosition) + inputChar + cantidad.substring(caretPosition);
                obtenerDinero(cantidad);
            } else if (inputChar == evt.VK_BACK_SPACE) {
                eliminarUltimoDigito();
                obtenerDinero(cantidad);
            } else {
                JOptionPane.showMessageDialog(this, "Solo se permiten números", "Error", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }

            System.out.println(cantidad);
            System.out.println(dinero);
        } catch (NumberFormatException e) {
            throw new NumberFormatException();
        }
    }//GEN-LAST:event_currencyOneKeyTyped

    private void currencyListOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyListOneActionPerformed
        cantidad = currencyOne.getText();
        System.out.println(cantidad);
        currency1 = (String) currencyListOne.getSelectedItem();
        //dinero = Double.valueOf(currencyTwo.getText());
    }//GEN-LAST:event_currencyListOneActionPerformed

    private void obtenerDinero(String cantidad) {
        if (cantidad.isEmpty()) {
            dinero = 0.0;
        } else {
            dinero = Double.valueOf(cantidad);
        }
        cambioDivisas();
        dinero = dinero * cambio;
        currencyTwo.setText(String.format("%.2f", dinero));
    }

    private void cambioDivisas() {
        if (null != currency1) {
            cambio = tasasDeCambio.getOrDefault(currency1, 0.14);
        }

//        if (null != currency1) {
//            switch (currency1) {
//                case "Bolivianos (Bs) a Dólar ($)":
//                    cambio = 0.14;
//                    break;
//                case "Bolivianos (Bs) a Euro (€)":
//                    cambio = 0.13;
//                    break;
//                case "Bolivianos (Bs) a Libras Esterlinas (£)":
//                    cambio = 0.12;
//                    break;
//                case "Bolivianos (Bs) a Yen Japonés (¥)":
//                    cambio = 20.00;
//                    break;
//                case "Bolivianos (Bs) a Won sur-coreano (₩)":
//                    cambio = 190.22;
//                    break;
//                default:
//                    cambio = 0.14;
//                    break;
//            }
//        }
    }

    private void eliminarUltimoDigito() {
        if (!cantidad.isEmpty()) {
            cantidad = cantidad.substring(0, cantidad.length() - 1);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CurrencyConverter;
    private javax.swing.JLabel CurrencyTitle;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem MainMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem TemperatureConverter;
    private javax.swing.JLabel currencyLabelOne;
    private javax.swing.JLabel currencyLabelTwo;
    private javax.swing.JComboBox<String> currencyListOne;
    private javax.swing.JTextField currencyOne;
    private javax.swing.JButton currencyReverse;
    private javax.swing.JLabel currencyTwo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator separator;
    // End of variables declaration//GEN-END:variables
}
