/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package window;

public class MainWindow extends javax.swing.JFrame {

    private String convertionTypeOne = "";

    public MainWindow() {
        initComponents();
        setSize(450, 300);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelMain = new javax.swing.JPanel();
        head1 = new javax.swing.JLabel();
        head2 = new javax.swing.JLabel();
        convertionTypes = new javax.swing.JComboBox<>();
        convertButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        MainMenu = new javax.swing.JMenuItem();
        CurrencyConverter = new javax.swing.JMenuItem();
        TemperatureConverter = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(15, 69, 113));
        setResizable(false);

        PanelMain.setBackground(new java.awt.Color(28, 35, 46));
        PanelMain.setLayout(new java.awt.GridBagLayout());

        head1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        head1.setForeground(new java.awt.Color(255, 255, 255));
        head1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head1.setText("Conversor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelMain.add(head1, gridBagConstraints);

        head2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        head2.setForeground(new java.awt.Color(204, 204, 204));
        head2.setText("Selecciona el tipo de conversión a realizar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelMain.add(head2, gridBagConstraints);

        convertionTypes.setBackground(new java.awt.Color(3, 72, 76));
        convertionTypes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        convertionTypes.setForeground(new java.awt.Color(255, 255, 255));
        convertionTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar --", "Moneda", "Temperatura" }));
        convertionTypes.setBorder(null);
        convertionTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertionTypesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 50);
        PanelMain.add(convertionTypes, gridBagConstraints);

        convertButton.setBackground(new java.awt.Color(3, 72, 76));
        convertButton.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        convertButton.setForeground(new java.awt.Color(255, 255, 255));
        convertButton.setText("Comenzar");
        convertButton.setBorderPainted(false);
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        PanelMain.add(convertButton, gridBagConstraints);

        MenuBar.setBackground(new java.awt.Color(28, 35, 46));
        MenuBar.setBorder(null);
        MenuBar.setForeground(new java.awt.Color(204, 204, 204));
        MenuBar.setBorderPainted(false);

        FileMenu.setBackground(new java.awt.Color(3, 72, 76));
        FileMenu.setBorder(null);
        FileMenu.setForeground(new java.awt.Color(204, 204, 204));
        FileMenu.setText("Archivo");
        FileMenu.setBorderPainted(false);
        FileMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        MainMenu.setBackground(new java.awt.Color(3, 72, 76));
        MainMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MainMenu.setForeground(new java.awt.Color(204, 204, 204));
        MainMenu.setText("Inicio");
        MainMenu.setEnabled(false);
        FileMenu.add(MainMenu);

        CurrencyConverter.setBackground(new java.awt.Color(3, 72, 76));
        CurrencyConverter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CurrencyConverter.setForeground(new java.awt.Color(204, 204, 204));
        CurrencyConverter.setText("Conversor de Moneda");
        CurrencyConverter.setBorder(null);
        CurrencyConverter.setBorderPainted(false);
        CurrencyConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyConverterActionPerformed(evt);
            }
        });
        FileMenu.add(CurrencyConverter);

        TemperatureConverter.setBackground(new java.awt.Color(3, 72, 76));
        TemperatureConverter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TemperatureConverter.setForeground(new java.awt.Color(204, 204, 204));
        TemperatureConverter.setText("Conversor de Temperatura");
        TemperatureConverter.setBorder(null);
        TemperatureConverter.setBorderPainted(false);
        TemperatureConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperatureConverterActionPerformed(evt);
            }
        });
        FileMenu.add(TemperatureConverter);

        separator.setBackground(new java.awt.Color(5, 172, 89));
        FileMenu.add(separator);

        Exit.setBackground(new java.awt.Color(3, 72, 76));
        Exit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(204, 204, 204));
        Exit.setText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        FileMenu.add(Exit);

        MenuBar.add(FileMenu);

        HelpMenu.setBackground(new java.awt.Color(3, 72, 76));
        HelpMenu.setForeground(new java.awt.Color(204, 204, 204));
        HelpMenu.setText("Ayuda");
        HelpMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MenuBar.add(HelpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        if (convertionTypeOne.equals("Moneda")) {
            CurrencyWindow currencyWindow = new CurrencyWindow();
            currencyWindow.setVisible(true);
            dispose();
        } else if (convertionTypeOne.equals("Temperatura")) {
            TemperatureWindow temperatureWindow = new TemperatureWindow();
            temperatureWindow.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void TemperatureConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperatureConverterActionPerformed
        TemperatureWindow temperatureWindow = new TemperatureWindow();
        temperatureWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_TemperatureConverterActionPerformed

    private void CurrencyConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyConverterActionPerformed
        CurrencyWindow currencyWindow = new CurrencyWindow();
        currencyWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_CurrencyConverterActionPerformed

    private void convertionTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertionTypesActionPerformed
        convertionTypeOne = (String) convertionTypes.getSelectedItem();
    }//GEN-LAST:event_convertionTypesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CurrencyConverter;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem MainMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JMenuItem TemperatureConverter;
    private javax.swing.JButton convertButton;
    private javax.swing.JComboBox<String> convertionTypes;
    private javax.swing.JLabel head1;
    private javax.swing.JLabel head2;
    private javax.swing.JPopupMenu.Separator separator;
    // End of variables declaration//GEN-END:variables
}
