/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package window;

/**
 *
 * @author eynar
 */
public class TemperatureWindow extends javax.swing.JFrame {

    /**
     * Creates new form currencyWindow
     */
    public TemperatureWindow() {
        initComponents();
        setSize(450, 300);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        TemperatureTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tempratureListOne = new javax.swing.JComboBox<>();
        tempratureListTwo = new javax.swing.JComboBox<>();
        temperatureOne = new javax.swing.JTextField();
        temperatureTwo = new javax.swing.JTextField();
        temperatureReverse = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        MainMenu = new javax.swing.JMenuItem();
        CurrencyConverter = new javax.swing.JMenuItem();
        TemperatureConverter = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 69, 113));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        TemperatureTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TemperatureTitle.setForeground(new java.awt.Color(255, 255, 255));
        TemperatureTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TemperatureTitle.setText("Conversor de Temperatura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(TemperatureTitle, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("De:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        tempratureListOne.setBackground(new java.awt.Color(58, 49, 50));
        tempratureListOne.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tempratureListOne.setForeground(new java.awt.Color(255, 255, 255));
        tempratureListOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tempratureListOne.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(tempratureListOne, gridBagConstraints);

        tempratureListTwo.setBackground(new java.awt.Color(58, 49, 50));
        tempratureListTwo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tempratureListTwo.setForeground(new java.awt.Color(255, 255, 255));
        tempratureListTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tempratureListTwo.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(tempratureListTwo, gridBagConstraints);

        temperatureOne.setBackground(new java.awt.Color(58, 49, 50));
        temperatureOne.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        temperatureOne.setForeground(new java.awt.Color(255, 255, 255));
        temperatureOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        temperatureOne.setCaretColor(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(temperatureOne, gridBagConstraints);

        temperatureTwo.setBackground(new java.awt.Color(58, 49, 50));
        temperatureTwo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        temperatureTwo.setForeground(new java.awt.Color(255, 255, 255));
        temperatureTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        temperatureTwo.setCaretColor(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(temperatureTwo, gridBagConstraints);

        temperatureReverse.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        temperatureReverse.setText("Reverse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(temperatureReverse, gridBagConstraints);

        MenuBar.setBackground(new java.awt.Color(15, 69, 113));
        MenuBar.setBorder(null);
        MenuBar.setForeground(new java.awt.Color(204, 204, 204));
        MenuBar.setBorderPainted(false);

        FileMenu.setBackground(new java.awt.Color(58, 49, 50));
        FileMenu.setBorder(null);
        FileMenu.setForeground(new java.awt.Color(204, 204, 204));
        FileMenu.setText("Archivo");
        FileMenu.setBorderPainted(false);
        FileMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        MainMenu.setBackground(new java.awt.Color(58, 49, 50));
        MainMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MainMenu.setForeground(new java.awt.Color(204, 204, 204));
        MainMenu.setText("Inicio");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        FileMenu.add(MainMenu);

        CurrencyConverter.setBackground(new java.awt.Color(58, 49, 50));
        CurrencyConverter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CurrencyConverter.setForeground(new java.awt.Color(204, 204, 204));
        CurrencyConverter.setText("Conversor de Moneda");
        CurrencyConverter.setBorder(null);
        CurrencyConverter.setBorderPainted(false);
        CurrencyConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyConverterActionPerformed(evt);
            }
        });
        FileMenu.add(CurrencyConverter);

        TemperatureConverter.setBackground(new java.awt.Color(58, 49, 50));
        TemperatureConverter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TemperatureConverter.setForeground(new java.awt.Color(204, 204, 204));
        TemperatureConverter.setText("Conversor de Temperatura");
        TemperatureConverter.setBorder(null);
        TemperatureConverter.setBorderPainted(false);
        TemperatureConverter.setEnabled(false);
        FileMenu.add(TemperatureConverter);

        separator.setBackground(new java.awt.Color(0, 157, 221));
        FileMenu.add(separator);

        Exit.setBackground(new java.awt.Color(58, 49, 50));
        Exit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(204, 204, 204));
        Exit.setText("Salir");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        FileMenu.add(Exit);

        MenuBar.add(FileMenu);

        HelpMenu.setBackground(new java.awt.Color(58, 49, 50));
        HelpMenu.setForeground(new java.awt.Color(204, 204, 204));
        HelpMenu.setText("Ayuda");
        HelpMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MenuBar.add(HelpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrencyConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyConverterActionPerformed
        CurrencyWindow currencyWindow = new CurrencyWindow();
        currencyWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_CurrencyConverterActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        MainWindow mainWindow = new MainWindow();
        mainWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_MainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CurrencyConverter;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem MainMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem TemperatureConverter;
    private javax.swing.JLabel TemperatureTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JTextField temperatureOne;
    private javax.swing.JButton temperatureReverse;
    private javax.swing.JTextField temperatureTwo;
    private javax.swing.JComboBox<String> tempratureListOne;
    private javax.swing.JComboBox<String> tempratureListTwo;
    // End of variables declaration//GEN-END:variables
}
